#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -Eq '^TASK-[0-9]+: .+'; then
  echo "Invalid commit message format."
  echo "Use format: TASK-123: Your message"
  exit 1
fi
